Traceback (most recent call last):
  File "/var/folders/93/4tspbrs900q0m61qlxy3g_9r0000gn/T/ipykernel_61593/984710998.py", line 34, in train_model
    model.fit(X_train, y_train)
  File "/Users/johnny/Documents/GitHub/MSAI490_HW4/.venv/lib/python3.9/site-packages/xgboost/core.py", line 730, in inner_f
    return func(**kwargs)
  File "/Users/johnny/Documents/GitHub/MSAI490_HW4/.venv/lib/python3.9/site-packages/xgboost/sklearn.py", line 1471, in fit
    raise ValueError(
ValueError: Invalid classes inferred from unique values of `y`.  Expected: [    0     1     2 ... 10691 10692 10693], got [  326   327   334 ... 18804 18806 18818]